const FREE_HOSTS='FREE_HOSTS';
const SESSIONS='SESSIONS';
const COOKIE_NAME='RCE-CONNECTION'
const CONNECTION_EXPIRATION=120000
export {
    FREE_HOSTS,
    SESSIONS,
    COOKIE_NAME,
    CONNECTION_EXPIRATION
}