version: '3'
services:
  rce:
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_PORT: ${REDIS_PORT}

      MYSQL_HOST_1: ${MYSQL_HOST_1}
      MYSQL_PORT_1: ${MYSQL_PORT_1}
      MYSQL_DATABASE_1: ${MYSQL_DATABASE_1}
      MYSQL_USER_1: ${MYSQL_USER_1}
      MYSQL_PASSWORD_1: ${MYSQL_PASSWORD_1}

      MYSQL_HOST_2: ${MYSQL_HOST_2}
      MYSQL_PORT_2: ${MYSQL_PORT_2}
      MYSQL_DATABASE_2: ${MYSQL_DATABASE_2}
      MYSQL_USER_2: ${MYSQL_USER_2}
      MYSQL_PASSWORD_2: ${MYSQL_PASSWORD_2}

      MYSQL_HOST_3: ${MYSQL_HOST_3}
      MYSQL_PORT_3: ${MYSQL_PORT_3}
      MYSQL_DATABASE_3: ${MYSQL_DATABASE_3}
      MYSQL_USER_3: ${MYSQL_USER_3}
      MYSQL_PASSWORD_3: ${MYSQL_PASSWORD_3}

      MYSQL_HOST_4: ${MYSQL_HOST_4}
      MYSQL_PORT_4: ${MYSQL_PORT_4}
      MYSQL_DATABASE_4: ${MYSQL_DATABASE_4}
      MYSQL_USER_4: ${MYSQL_USER_4}
      MYSQL_PASSWORD_4: ${MYSQL_PASSWORD_4}

      REACT_APP_NODE_SERVER_HOST: ${REACT_APP_NODE_SERVER_HOST}
      REACT_APP_NODE_SERVER_PORT: ${REACT_APP_NODE_SERVER_PORT}
      REACT_SERVER_HOST: ${REACT_SERVER_HOST}
      REACT_SERVER_PORT: ${REACT_SERVER_PORT}

      NODE_SERVER_HOST: ${NODE_SERVER_HOST}
      NODE_SERVER_PORT: ${NODE_SERVER_PORT}
      NODE_SERVER_IP: ${NODE_SERVER_IP}

      JWT_SECRET: ${JWT_SECRET}

    ports:
        - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}
    depends_on:
      - mysqldb1
      - mysqldb2
      - mysqldb3
      - mysqldb4
      - redis

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: rce-client
    container_name: rce-client
    command: npm start
    environment:
      REACT_APP_NODE_SERVER_HOST: ${REACT_APP_NODE_SERVER_HOST}
      REACT_APP_NODE_SERVER_PORT: ${REACT_APP_NODE_SERVER_PORT}
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - rce
    ports:
      - ${REACT_SERVER_PORT}:${REACT_SERVER_PORT}

  mysqldb1:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_1}
      MYSQL_USER: ${MYSQL_USER_1}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_1}
      MYSQL_PORT: ${MYSQL_PORT_1}
      MYSQL_HOST: ${MYSQL_HOST_1}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mysqldb2:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_2}
      MYSQL_USER: ${MYSQL_USER_2}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_2}
      MYSQL_PORT: ${MYSQL_PORT_2}
      MYSQL_HOST: ${MYSQL_HOST_2}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mysqldb3:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_3}
      MYSQL_USER: ${MYSQL_USER_3}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_3}
      MYSQL_PORT: ${MYSQL_PORT_3}
      MYSQL_HOST: ${MYSQL_HOST_3}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mysqldb4:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_4}
      MYSQL_USER: ${MYSQL_USER_4}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_4}
      MYSQL_PORT: ${MYSQL_PORT_4}
      MYSQL_HOST: ${MYSQL_HOST_4}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
